# Generated by Django 4.2.4 on 2023-08-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='email',
            new_name='user_id',
        ),
    ]
